import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import { createHash } from "node:crypto";
import openapiTS, { astToString } from "openapi-typescript";
import YAML from "yaml";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const methods = new Set(["get", "post", "put", "patch", "delete"]);

export async function buildArtifacts(spec) {
  const fingerprint = createHash("sha256").update(JSON.stringify(spec)).digest("hex");
  // The generator normalizes discriminator schemas in place; preserve the source
  // so repeated generation in one process has identical output.
  const ast = await openapiTS(structuredClone(spec), { alphabetize: true, exportType: true });
  const mapping = Object.entries(spec.paths).flatMap(([route, item]) =>
    Object.entries(item).filter(([method]) => methods.has(method)).map(([method, operation]) => ({
      operationId: operation.operationId,
      method: method.toUpperCase(),
      path: `/api/v1${route}`,
      issue: Number(operation["x-issue"].split("/").at(-1)),
      rebuildOwner: operation["x-rebuild-owner"],
    })),
  ).sort((a, b) => a.operationId.localeCompare(b.operationId, "en"));
  return new Map([
    ["packages/api-client/src/generated/schema.ts", `/**\n * Generated by openapi-typescript 7.13.0 from contracts/openapi.yaml.\n * Contract SHA-256: ${fingerprint}\n * Do not edit manually. Run yarn api:generate.\n */\n\n${astToString(ast)}`],
    ["contracts/operation-issues.json", `${JSON.stringify(mapping, null, 2)}\n`],
  ]);
}

export async function saveArtifacts(artifacts, outputRoot, check) {
  for (const [relative, generated] of artifacts) {
    const target = path.join(outputRoot, relative);
    if (check) {
      const current = await readFile(target, "utf8").catch(() => null);
      if (current !== generated) throw new Error(`Generated contract drift: ${relative}. Run yarn api:generate.`);
    } else {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, generated);
    }
  }
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const check = process.argv.includes("--check");
  const spec = YAML.parse(await readFile(path.join(root, "contracts/openapi.yaml"), "utf8"));
  await saveArtifacts(await buildArtifacts(spec), root, check);
  console.log(check ? "Generated client and operation mapping are current." : "Generated client and operation mapping updated.");
}
